I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    init 1 python:
  File "game/script.rpy", line 6, in script
    init 1 python:
  File "game/script.rpy", line 7, in <module>
    import createDictionaries as f
NameError: name 'renpy' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpengine\renpy-7.4.10-sdk\renpy\bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "D:\renpengine\renpy-7.4.10-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 6, in script
    init 1 python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 6, in script
    init 1 python:
  File "D:\renpengine\renpy-7.4.10-sdk\renpy\ast.py", line 1111, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpengine\renpy-7.4.10-sdk\renpy\python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    import createDictionaries as f
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "D:\renpengine\renpy-7.4.10-sdk\renpy\loader.py", line 1007, in load_module
    exec(code, mod.__dict__) # type: ignore
  File "python-packages/createDictionaries.py", line 45, in <module>
  File "python-packages/createDictionaries.py", line 25, in readCSVFile
NameError: name 'renpy' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.0.22062402
Wind and Spirit 1.0
Tue Jul  5 16:00:52 2022
